name: backend
description: Mock flight‐authorization server

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  uuid: ^3.0.6 # <-- add this line
  built_value: ^8.4.0
  built_collection: ^5.1.1
# no need for flutter or any flutter‑specific deps here
