name: flight_auth_backend
description: Mock server
environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  uuid: ^3.0.6
  app:
    path: ../ # <-- tells backend about your "app" package
